#!/bin/sh


generate_etsi() {
	"${input}" "${country_dir}"
	local input_file="$1"
	local output_dir="$2"
	local config_file="$3"
}


generate_entry() {
	local input_file="$1"
	local output_dir="$2"
	local config_file="$3"

	local start="no"
	local result=1
	local country=""

	while IFS=" " read -r line; do
		# Country
		echo "$line" | grep "^country" 1>/dev/null 2>/dev/null
		result="$?"
		if [ "${result}" -eq 0 ]; then
			start="yes"
			country="$(echo "${line}" | cut -d' ' -f2)"
			country="${country%%:}"
			country="$(echo "${country}" | tr '[:lower:]' '[:upper:]')"
			echo "Generate build config and regdb settings for ${country}"

			{
				printf 'config WIRELESS_REGDB_COUNTRY_%s\n' "${country}"
				printf '\tbool "Select Country %s"\n' "${country}"
				printf '\tdefault n\n\n'
			} >> "${config_file}"
		fi

		# ETSI
		echo "$line" | grep "^wmmrule ETSI:" 1>/dev/null 2>/dev/null
		result="$?"
		if [ "${result}" -eq 0 ]; then
			start="yes"
			country="$(echo "${line}" | cut -d' ' -f2)"
			country="${country%%:}"
			country="$(echo "${country}" | tr '[:lower:]' '[:upper:]')"
			echo "Generate ETSI"
		fi

		[ "${start}" = "yes" ] && {
			echo "${line}" >> "${output_dir}/${country}"
		}

		[ -z "$line" ] && [ "$start" = "yes" ] && {
			start="no"
		}

	done < "${input_file}"
}

main() {
	local input="$1"

	# Set output file
	local output=""
	output="$(readlink -f "$0")"
	pkgdir="${output%/*}"

	local config_file="${pkgdir}/config/Config-countries.in"
	local country_dir="${pkgdir}/countries"

	[ -f "$input" ] || {
		echo "Please provide the file db.txt from wireless-regdb"
		exit 1
	}

	rm -rf "${config_file}"
	rm -rf "${country_dir}"
	mkdir -p "${country_dir}"

	echo "# Autogenerated Config.in for country selection in regdb" > "${config_file}"
	echo "menu \"Countries\"" >> "${config_file}"
	generate_entry "${input}" "${country_dir}" "${config_file}"
	echo "endmenu" >> "${config_file}"
}

main "$@"
